sudo: required
services:
  - docker

before_install:
  - docker build -t mlallai/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mlallai/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  name: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-343299863709"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
