sudo: required
services:
  - docker

before_install:
  - docker build -t mlallai/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mlallai/docker-react npm run test -- --watchAll=false
